# Generated by Django 5.1.5 on 2025-01-24 21:51

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('petite_description', models.TextField()),
                ('grande_description', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='titre')),
                ('image', models.ImageField(upload_to='service/pics')),
                ('icone', models.CharField(choices=[('bi bi-briefcase', 'Création Web'), ('bi bi-card-checklist', 'E-commerce'), ('bi bi-bar-chart', 'SEO & Marketing'), ('bi bi-binoculars', 'Applications Web'), ('bi bi-brightness-high', 'UI/UX Design'), ('bi bi-calendar4-week', 'Maintenance')], max_length=25)),
                ('icone_couleur', models.CharField(choices=[('#f57813', 'Orange - Création Web'), ('#15a04a', 'Vert - E-commerce'), ('#d90769', 'Rose - SEO & Marketing'), ('#15bfbc', 'Turquoise - Applications Web'), ('#f5cf13', 'Jaune - UI/UX Design'), ('#1335f5', 'Bleu - Maintenance')], max_length=7)),
            ],
        ),
    ]
