# Generated by Django 5.1.5 on 2025-01-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlyfree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icone',
            field=models.CharField(choices=[('bi bi-briefcase', 'Icône pour Création Web'), ('bi bi-card-checklist', 'Icône pour E-commerce'), ('bi bi-bar-chart', 'Icône pour SEO & Marketing'), ('bi bi-binoculars', 'Icône pour Applications Web'), ('bi bi-brightness-high', 'Icône pour UI/UX Design'), ('bi bi-calendar4-week', 'Icône pour Maintenance')], max_length=25),
        ),
    ]
