# Generated by Django 5.1.5 on 2025-01-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlyfree', '0002_alter_service_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service/pics'),
        ),
    ]
