# Generated by Django 5.1.5 on 2025-01-25 00:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devlyfree', '0003_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='titre', unique=True),
        ),
    ]
