# Generated by Django 5.1.5 on 2025-01-31 02:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devlyfree', '0007_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='titre'),
        ),
    ]
