# Generated by Django 5.1.5 on 2025-02-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlyfree', '0008_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description pour le SEO - Idéalement entre 150 et 160 caractères', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title tag pour le SEO - Idéalement entre 50 et 60 caractères', max_length=60, null=True),
        ),
    ]
