# Generated by Django 5.1.5 on 2025-02-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlyfree', '0009_service_meta_description_service_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Accueil'), ('about', 'À propos'), ('services', 'Liste des Services'), ('portfolio', 'Liste des Projets'), ('blog', 'Blog'), ('contact', 'Contact')], max_length=20, unique=True)),
                ('meta_title', models.CharField(help_text='Title tag pour le SEO - Idéalement entre 50 et 60 caractères', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description pour le SEO - Idéalement entre 150 et 160 caractères', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=200)),
            ],
            options={
                'verbose_name': 'SEO Page',
                'verbose_name_plural': 'SEO Pages',
                'ordering': ['page'],
            },
        ),
    ]
