# Generated by Django 5.1.5 on 2025-02-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlyfree', '0010_pageseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=200, null=True),
        ),
    ]
