# Generated by Django 5.1.5 on 2025-02-11 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlyfree', '0011_service_meta_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='devlyfree.category'),
        ),
    ]
