# Generated by Django 5.1.5 on 2025-02-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlyfree', '0012_alter_article_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='devlyfree.tag'),
        ),
    ]
