# Generated by Django 5.1.5 on 2025-02-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devlyfree', '0014_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
